package Game;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Anahuel
 */
public class GAME extends javax.swing.JFrame {

    /**
     * Creates new form GAME
     */
    public GAME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errores = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        msjerror = new javax.swing.JLabel();
        mensaje = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        labelmsj = new javax.swing.JLabel();
        reinicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bmazo = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jcarta0 = new javax.swing.JButton();
        jcarta4 = new javax.swing.JButton();
        jcarta2 = new javax.swing.JButton();
        jcarta6 = new javax.swing.JButton();
        jcarta8 = new javax.swing.JButton();
        jcarta1 = new javax.swing.JButton();
        jcarta3 = new javax.swing.JButton();
        jcarta5 = new javax.swing.JButton();
        jcarta7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelplayer = new javax.swing.JLabel();
        labelcasa = new javax.swing.JLabel();
        bquedo = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        ccarta0 = new javax.swing.JButton();
        ccarta3 = new javax.swing.JButton();
        ccarta1 = new javax.swing.JButton();
        ccarta5 = new javax.swing.JButton();
        ccarta7 = new javax.swing.JButton();
        ccarta2 = new javax.swing.JButton();
        ccarta4 = new javax.swing.JButton();
        ccarta6 = new javax.swing.JButton();
        ccarta8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        textfmazos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcarta10 = new javax.swing.JButton();
        jcarta9 = new javax.swing.JButton();
        ccarta9 = new javax.swing.JButton();
        ccarta10 = new javax.swing.JButton();

        errores.setTitle("ERROR");
        errores.setMaximumSize(new java.awt.Dimension(400, 202));
        errores.setMinimumSize(new java.awt.Dimension(400, 202));

        jPanel3.setMaximumSize(new java.awt.Dimension(400, 202));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 202));

        msjerror.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        msjerror.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(msjerror, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(msjerror, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout erroresLayout = new javax.swing.GroupLayout(errores.getContentPane());
        errores.getContentPane().setLayout(erroresLayout);
        erroresLayout.setHorizontalGroup(
            erroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        erroresLayout.setVerticalGroup(
            erroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erroresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mensaje.setTitle("Mensaje");
        mensaje.setMinimumSize(new java.awt.Dimension(380, 278));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelmsj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelmsj.setText("jLabel4");

        reinicio.setText("REINICIAR");
        reinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(labelmsj, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(reinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labelmsj, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(reinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout mensajeLayout = new javax.swing.GroupLayout(mensaje.getContentPane());
        mensaje.getContentPane().setLayout(mensajeLayout);
        mensajeLayout.setHorizontalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mensajeLayout.setVerticalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1326, 730));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel4.setText("BlackJack by Anahuel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(441, 441, 441))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        bmazo.setBackground(new java.awt.Color(0, 0, 0));
        bmazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/IMAGENES/icon deck_1.png"))); // NOI18N
        bmazo.setToolTipText("");
        bmazo.setEnabled(false);
        bmazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmazoActionPerformed(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(0, 102, 0));
        jPanel14.setPreferredSize(new java.awt.Dimension(1306, 200));

        jcarta0.setBackground(new java.awt.Color(0, 102, 0));
        jcarta0.setPreferredSize(new java.awt.Dimension(171, 209));

        jcarta4.setBackground(new java.awt.Color(0, 102, 0));
        jcarta4.setPreferredSize(new java.awt.Dimension(171, 209));

        jcarta2.setBackground(new java.awt.Color(0, 102, 0));
        jcarta2.setPreferredSize(new java.awt.Dimension(171, 209));

        jcarta6.setBackground(new java.awt.Color(0, 102, 0));
        jcarta6.setPreferredSize(new java.awt.Dimension(171, 209));

        jcarta8.setBackground(new java.awt.Color(0, 102, 0));
        jcarta8.setPreferredSize(new java.awt.Dimension(171, 209));

        jcarta1.setBackground(new java.awt.Color(0, 102, 0));
        jcarta1.setPreferredSize(new java.awt.Dimension(171, 209));

        jcarta3.setBackground(new java.awt.Color(0, 102, 0));
        jcarta3.setPreferredSize(new java.awt.Dimension(171, 209));

        jcarta5.setBackground(new java.awt.Color(0, 102, 0));
        jcarta5.setPreferredSize(new java.awt.Dimension(171, 209));

        jcarta7.setBackground(new java.awt.Color(0, 102, 0));
        jcarta7.setName(""); // NOI18N
        jcarta7.setPreferredSize(new java.awt.Dimension(171, 209));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcarta7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcarta5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcarta0, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcarta4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcarta6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcarta8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcarta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcarta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jcarta0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcarta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcarta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcarta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcarta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcarta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Su Score:");

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CASA");

        labelplayer.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        labelplayer.setForeground(new java.awt.Color(255, 255, 255));

        labelcasa.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        labelcasa.setForeground(new java.awt.Color(255, 255, 255));

        bquedo.setText("QUEDARSE");
        bquedo.setEnabled(false);
        bquedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquedoActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(0, 102, 0));
        jPanel15.setPreferredSize(new java.awt.Dimension(1306, 200));

        ccarta0.setBackground(new java.awt.Color(0, 102, 0));
        ccarta0.setPreferredSize(new java.awt.Dimension(171, 209));

        ccarta3.setBackground(new java.awt.Color(0, 102, 0));
        ccarta3.setPreferredSize(new java.awt.Dimension(171, 209));

        ccarta1.setBackground(new java.awt.Color(0, 102, 0));
        ccarta1.setPreferredSize(new java.awt.Dimension(171, 209));

        ccarta5.setBackground(new java.awt.Color(0, 102, 0));
        ccarta5.setPreferredSize(new java.awt.Dimension(171, 209));

        ccarta7.setBackground(new java.awt.Color(0, 102, 0));
        ccarta7.setPreferredSize(new java.awt.Dimension(171, 209));

        ccarta2.setBackground(new java.awt.Color(0, 102, 0));
        ccarta2.setPreferredSize(new java.awt.Dimension(171, 209));

        ccarta4.setBackground(new java.awt.Color(0, 102, 0));
        ccarta4.setPreferredSize(new java.awt.Dimension(171, 209));

        ccarta6.setBackground(new java.awt.Color(0, 102, 0));
        ccarta6.setPreferredSize(new java.awt.Dimension(171, 209));

        ccarta8.setBackground(new java.awt.Color(0, 102, 0));
        ccarta8.setName(""); // NOI18N
        ccarta8.setPreferredSize(new java.awt.Dimension(171, 209));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ccarta8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ccarta6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccarta4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccarta0, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccarta5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccarta7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccarta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ccarta0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ccarta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ccarta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ccarta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ccarta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ccarta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ccarta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textfmazos.setText("1");
        textfmazos.setToolTipText("numeros");
        textfmazos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfmazosKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MAZOS A USAR");

        jcarta10.setBackground(new java.awt.Color(0, 0, 0));
        jcarta10.setMaximumSize(new java.awt.Dimension(171, 209));
        jcarta10.setMinimumSize(new java.awt.Dimension(171, 209));
        jcarta10.setPreferredSize(new java.awt.Dimension(171, 209));

        jcarta9.setBackground(new java.awt.Color(0, 0, 0));
        jcarta9.setMaximumSize(new java.awt.Dimension(171, 209));
        jcarta9.setMinimumSize(new java.awt.Dimension(171, 209));
        jcarta9.setPreferredSize(new java.awt.Dimension(171, 209));

        ccarta9.setBackground(new java.awt.Color(0, 0, 0));
        ccarta9.setMaximumSize(new java.awt.Dimension(171, 209));
        ccarta9.setMinimumSize(new java.awt.Dimension(171, 209));
        ccarta9.setPreferredSize(new java.awt.Dimension(171, 209));

        ccarta10.setBackground(new java.awt.Color(0, 0, 0));
        ccarta10.setMaximumSize(new java.awt.Dimension(171, 209));
        ccarta10.setMinimumSize(new java.awt.Dimension(171, 209));
        ccarta10.setPreferredSize(new java.awt.Dimension(171, 209));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ccarta9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ccarta10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textfmazos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addComponent(bmazo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(bquedo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(jcarta10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcarta9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfmazos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bquedo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bmazo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcarta10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcarta9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ccarta9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ccarta10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(449, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //atributos
    MAZO deck;
    JUGADOR mano;
    JUGADOR manoCasa;

    private boolean primera_mano() {
        int mzo = 0;
        mzo = num_mazos();
        boolean ok = false;
        if (mzo != 0) {
            deck = new MAZO(mzo);
            mano = new JUGADOR();
            manoCasa = new JUGADOR();
            mano.pone_carta(deck.Entrega_Carta());
            manoCasa.pone_carta(deck.Entrega_Carta());
            dibuja_mesa();
            actualiza_contador();
            ok = true;
        } else {
            msjerror.setText("DEBE INGRESAR NUMERO ENTRE 1 Y 4");
            errores.setVisible(true);
            ok = false;
        }
        return ok;
        //textfmazos
    }

    private void actualiza_contador() {
        labelplayer.setText("" + mano.Cuenta_Cartas() + " / " + mano.Cuenta_opcion());
        labelcasa.setText("" + manoCasa.Cuenta_Cartas() + " / " + manoCasa.Cuenta_opcion());
    }

    private void dibuja_mesa() {
        int recorrido = 0;
        do {
            int num = mano.getJugadas(recorrido).getNumero();
            int pinta = mano.getJugadas(recorrido).getTipo();
            dibuja_carta_player(recorrido, num, pinta);
            recorrido++;
        } while ((recorrido < 11) && mano.getJugadas(recorrido) != null);
        recorrido = 0;
        do {
            int num = manoCasa.getJugadas(recorrido).getValor();
            int pinta = manoCasa.getJugadas(recorrido).getTipo();
            dibuja_carta_Casa(recorrido, num, pinta);
            recorrido++;
        } while ((recorrido < 11) && manoCasa.getJugadas(recorrido) != null);
    }

    private void dibuja_carta_player(int pos, int num, int pta) {
        ICONOS imagen = new ICONOS();
        switch (pos) {
            case 0:
                jcarta0.setIcon(imagen.getImagenes(pta, num));
                break;
            case 1:
                jcarta1.setIcon(imagen.getImagenes(pta, num));
                break;
            case 2:
                jcarta2.setIcon(imagen.getImagenes(pta, num));
                break;
            case 3:
                jcarta3.setIcon(imagen.getImagenes(pta, num));
                break;
            case 4:
                jcarta4.setIcon(imagen.getImagenes(pta, num));
                break;
            case 5:
                jcarta5.setIcon(imagen.getImagenes(pta, num));
                break;
            case 6:
                jcarta6.setIcon(imagen.getImagenes(pta, num));
                break;
            case 7:
                jcarta7.setIcon(imagen.getImagenes(pta, num));
                break;
            case 8:
                jcarta8.setIcon(imagen.getImagenes(pta, num));
                break;
            case 9:
                jcarta9.setIcon(imagen.getImagenes(pta, num));
                break;
            case 10:
                jcarta10.setIcon(imagen.getImagenes(pta, num));
                break;
        }
    }

    private void dibuja_carta_Casa(int pos, int num, int pta) {
        ICONOS imagen = new ICONOS();
        switch (pos) {
            case 0:
                ccarta0.setIcon(imagen.getImagenes(pta, num));
                break;
            case 1:
                ccarta1.setIcon(imagen.getImagenes(pta, num));
                break;
            case 2:
                ccarta2.setIcon(imagen.getImagenes(pta, num));
                break;
            case 3:
                ccarta3.setIcon(imagen.getImagenes(pta, num));
                break;
            case 4:
                ccarta4.setIcon(imagen.getImagenes(pta, num));
                break;
            case 5:
                ccarta5.setIcon(imagen.getImagenes(pta, num));
                break;
            case 6:
                ccarta6.setIcon(imagen.getImagenes(pta, num));
                break;
            case 7:
                ccarta7.setIcon(imagen.getImagenes(pta, num));
                break;
            case 8:
                ccarta8.setIcon(imagen.getImagenes(pta, num));
                break;
            case 9:
                ccarta9.setIcon(imagen.getImagenes(pta, num));
                break;
            case 10:
                ccarta10.setIcon(imagen.getImagenes(pta, num));
                break;
        }
    }

    private int num_mazos() {
        int num = 0;
        try {
            if (textfmazos.getText() != null && Integer.parseInt(textfmazos.getText()) < 5 && Integer.parseInt(textfmazos.getText()) > 0) {
                num = Integer.parseInt(textfmazos.getText());
            }
        } catch (Exception e) {//fallo en texto = no numerico
            errores.setVisible(true);
            msjerror.setText("numero fuera de rango");
        }
        return num;
    }

    private void bmazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmazoActionPerformed

        mano.pone_carta(deck.Entrega_Carta());
        dibuja_mesa();
        actualiza_contador();
        revisa_maximo();

    }//GEN-LAST:event_bmazoActionPerformed

    private void revisa_maximo() {
        int puntos = mano.Cuenta_Cartas();
        if (puntos > 21) {
            bmazo.setEnabled(false);
            bquedo.setEnabled(false);
            mensaje.setVisible(true);
            labelmsj.setText("Te has pasado, Pierdes!");
        }
    }

    private void bquedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquedoActionPerformed
        //aca juega la IA
        bmazo.setEnabled(false);
        bquedo.setEnabled(false);
        boolean jugando = true;
        int puntaje_player;
        if (mano.Cuenta_opcion() == 21) {
            puntaje_player = 21;
        } else {
            puntaje_player = mano.Cuenta_Cartas();
        }
        int my_puntaje = manoCasa.Cuenta_Cartas();

        while (jugando == true) {

            if (my_puntaje < puntaje_player) {
                manoCasa.pone_carta(deck.Entrega_Carta());
                dibuja_mesa();
                actualiza_contador();
                my_puntaje = manoCasa.Cuenta_Cartas();
                if (manoCasa.Cuenta_opcion() == 21) {
                    jugando = false;
                    perdedor();
                }
                if (dentro_del_maximo() == false) {
                    jugando = false;
                    ganador();
                }
            } else {
                jugando = false;
                perdedor();
            }
        }
    }//GEN-LAST:event_bquedoActionPerformed

    private boolean dentro_del_maximo() {
        if (manoCasa.Cuenta_Cartas() <= 21) {
            return true;
        } else {
            return false;
        }
    }

    private void ganador() {//gana jugador
        mensaje.setVisible(true);
        labelmsj.setText("has Ganado!");
    }

    private void perdedor() {//gana IA
        mensaje.setVisible(true);
        labelmsj.setText("venci, tu Pierdes!");
    }

    private void reinicio() {//reinicio con la primera jugada
        jButton1.setEnabled(true);
        ccarta0.setIcon(null);
        ccarta1.setIcon(null);
        ccarta2.setIcon(null);
        ccarta3.setIcon(null);
        ccarta4.setIcon(null);
        ccarta5.setIcon(null);
        ccarta6.setIcon(null);
        ccarta7.setIcon(null);
        ccarta8.setIcon(null);
        ccarta9.setIcon(null);
        ccarta10.setIcon(null);
        jcarta0.setIcon(null);
        jcarta1.setIcon(null);
        jcarta2.setIcon(null);
        jcarta3.setIcon(null);
        jcarta4.setIcon(null);
        jcarta5.setIcon(null);
        jcarta6.setIcon(null);
        jcarta7.setIcon(null);
        jcarta8.setIcon(null);
        jcarta9.setIcon(null);
        jcarta10.setIcon(null);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // habilita el juego :D
        //primera mano
        boolean ok = false;
        ok = primera_mano();
        if (ok == true) {
            bmazo.setEnabled(true);
            bquedo.setEnabled(true);
            jButton1.setEnabled(false);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void textfmazosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfmazosKeyTyped

    }//GEN-LAST:event_textfmazosKeyTyped

    private void reinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinicioActionPerformed
        reinicio();
        mensaje.setVisible(false);
    }//GEN-LAST:event_reinicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmazo;
    private javax.swing.JButton bquedo;
    private javax.swing.JButton ccarta0;
    private javax.swing.JButton ccarta1;
    private javax.swing.JButton ccarta10;
    private javax.swing.JButton ccarta2;
    private javax.swing.JButton ccarta3;
    private javax.swing.JButton ccarta4;
    private javax.swing.JButton ccarta5;
    private javax.swing.JButton ccarta6;
    private javax.swing.JButton ccarta7;
    private javax.swing.JButton ccarta8;
    private javax.swing.JButton ccarta9;
    private javax.swing.JDialog errores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jcarta0;
    private javax.swing.JButton jcarta1;
    private javax.swing.JButton jcarta10;
    private javax.swing.JButton jcarta2;
    private javax.swing.JButton jcarta3;
    private javax.swing.JButton jcarta4;
    private javax.swing.JButton jcarta5;
    private javax.swing.JButton jcarta6;
    private javax.swing.JButton jcarta7;
    private javax.swing.JButton jcarta8;
    private javax.swing.JButton jcarta9;
    private javax.swing.JLabel labelcasa;
    private javax.swing.JLabel labelmsj;
    private javax.swing.JLabel labelplayer;
    private javax.swing.JDialog mensaje;
    private javax.swing.JLabel msjerror;
    private javax.swing.JButton reinicio;
    private javax.swing.JTextField textfmazos;
    // End of variables declaration//GEN-END:variables
}
